name = "Cim"
uuid = "b8bf244d-ef81-4004-af7f-81da40f35d23"
authors = ["Jiayi Zhang"]
version = "1.0.0-DEV"

[compat]
julia = "1.11"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
